version: "3"

services:

  influxdb:
    restart: always
    image: influxdb:2.1.1
    restart: on-failure:10
    ports:
      - 8086:8086

  coap:
    restart: always
    image: ocfcloud/coap-gateway

  grafana:
    restart: always
    image: grafana/grafana-oss:8.4.3
    depends_on:
      - influxdb
    ports:
      - 3000:3000

  mosquitto-container:
    restart: always
    image: eclipse-mosquitto
    ports:
      - 1883:1883

 