version: "3"

services:
  pythonapp:
    build: ./
    command: python subscriber_server/mqtt_subscriber.py
    ports:
      - 1883:1883

  influxdb:
    restart: always
    image: influxdb:2.1.1
    ports:
      - 8086:8086

  coap:
    restart: always
    image: ocfcloud/coap-gateway

  grafana:
    restart: always
    image: grafana/grafana-oss:8.4.3
    depends_on:
      - influxdb
    ports:
      - 3000:3000


 